### PR TITLE
Adds Pagination to find project

### LINKED ISSUE #55: Action fails to find project when there are more than 30 projects
The action can't find the project if there are more than 30 projects, since the API being used to list all projects is paginated and returns at most 30 projects (by default).

If this API is going to be used, then it will need to be paginated.

It would be easier (and faster) to ask for the project id instead of trying to determine it from the URL (a little more work for user but I think a decent tradeoff)

### PR DESCRIPTION
**Pull request by tspascoal**
closes #55

Adds pagination to find project.

If the project being looked for wasn't in the 30 first results then the project wouldn't be found.

The search is now paginaged and the page size has been increased to 100 so search is more efficient when the number of projects is large

### CODE REVIEW

**Comment by srggrs** [comment]
Hi @tspascoal sorry for not being present... Did you test this? Also how do you feel like jumping on board as admin of this repo?

**Comment by tspascoal** [comment]
@srggrs Sorry for the delay, completely missed the notification.

Yes I've tested this.

I don't think I would be of much value by being added as admin to be honest

**Comment by lindluni** [comment]
@srggrs, any chance we can merge this so we can consume it upstream?

**Comment by srggrs** [comment]
> @srggrs, any chance we can merge this so we can consume it upstream?

working on it today @lindluni so watch for the new release

**Pull request merged**
