### PR TITLE
Update image version used in action

### LINKED ISSUE #67: "Nothing to be done on this action: pull_request_target" when using v1.2.1
Running the latest version of this action, v1.2.1, i see the output: "Nothing to be done on this action: pull_request_target".

Screen Shot 2021-03-18 at 3 13 39 PM

It looks like the action is pulling an old docker image: srggrs/assign-one-project-github-action:1.2.0, despite using v1.2.1 of the action.

### PR DESCRIPTION
**Pull request by nr-kkenney**
~~* Update the image version from 1.2.0 -> 1.2.1 (current latest).~~

Update the action to use local Dockerfile.

Close #67

### CODE REVIEW

**Comment by nr-kkenney** [comment]
This looked like a simple change, but is my first time with something like this 🙈 

Feel free to edit / close this if I did something incorrect 👍 .

**Comment by tspascoal** [comment]
Just a note, if

If instead of specifying an image name a `Dockerfile` is specified like this:

```yaml
  image: 'Dockerfile'
```

then no need to have the image hosted on dockerhub, it will be built on the fly by the agent as needed using the `Dockerfile`

**Comment by mondeja** [comment]
Please, @nr-kkenney, could you update the `image` field as has pointed @tspascoal? Furthermore, @srggrs, could you take a look at this PR as soon as you can?

**Comment by srggrs** [comment]
Close #67

**Comment by srggrs** [comment]
Sorry guys I've been a bit sloppy lately... merging and releasing it

**Comment by srggrs** [comment]
@mondeja version 1.2.1 should be updated with these changes, let me know if there are any issues

**Pull request merged**
